on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'Calvin'

jobs:
  greet:
    runs-on: [self-hosted, macOS]
    steps:
      - run: echo "Hello, ${{ github.event.inputs.name }}!"
